### ISSUE TITLE
Connect Web Frontend and Backend

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#149]
Title:
Issue created for joining web frontend and backend applications.

Category:
- [x] Feature Request
- [x]  Enhancement
- [ ]  Design Proposal
- [ ]  Specification Clarification
- [ ]  Planning Discussion

Objective:
Add api request methods to frontend components
Detailed Description:
We should create connections between web frontend components and backend to send requests to backend endpoints. Connection between mobile and backend should also be implemented in the next step.
Related Team Members:
- Mert Cengiz @MertCengiz 
- Eren Pakelgil @erenpakelgil 

Proposed Timeline:
19.10.2024

**Comment by erenpakelgil** [comment]
Created the initial version of register and login components, imported api instance in components with @MertCengiz. Router should be integrated in main app file and the connection of frontend to backend endpoints will be tested.

**Comment by MertCengiz** [comment]
Router was integrated to the main app file with many components just after the collaborative session with @erenpakelgil . Due to the unfortunate situation that the database didn't work, the connection between frontend and backend couldn't tested. Moreover, even though many features are adapted to the new project, there could be some mistakenly remaining parts from Artifact; especially, **Search Results Component** is under high risk. Related Pull Request is available [here](https://github.com/bounswe/bounswe2024group7/pull/151).

**Comment by sametaln** [comment]
Why database did not work? Can you elaborate further?

**Comment by sametaln** [comment]
Connection and database creation successfull in branch `Issue#149`. Not pushed yet.
