### ISSUE TITLE
Creating Class Diagrams

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#30]
A detailed class diagram according to [Requirements](./wiki/Requirements) should be implemented in any drawing application.

**Comment by MertCengiz** [comment]
Review and feedback needed for this diagram.  The diagram is accessible [there](https://github.com/bounswe/bounswe2024group7/blob/main/Class-Diagram.mmd)

**Comment by oguzhekim** [comment]
I made some changes to the class diagram:
1. I removed some of the getters and setters to avoid boilerplate code. I tried to keep only relevant getters that we will use in our implementation. Maybe we can add a note saying that "the attributes without getters and setters should have one". 
2. The main actions are now done on profile class rather than user.
3. Changed the class of some methods. For example I moved getPostsOfUser from profile class to post class.
4. Added like, image, wikidataresult classes.
5. I tried to show cardinality between classes (one-to-one, one-to-many etc.)

You can see the diagram [here](https://www.mermaidchart.com/app/projects/4dd980fe-f91e-4ed6-aae3-3822892c1d06/diagrams/44542408-e734-485b-8998-289105403a80/version/v0.1/edit). Please reach me if you can't access it. I might have deleted something useful from previous version or changed the logic unnecessarily. So, please give feedback of this new version and make changes to the diagram if necessary.

**Comment by oguzhekim** [comment]
The "Feed" class is removed and its functionality is moved to the "User" class based on the feedback from TA. I created a wikipage for the last version of the new class diagram. We can delete the former version and rename this one once we settle with this diagram. It is accessible here: [Class Diagram v2](https://github.com/bounswe/bounswe2024group7/wiki/Class-Diagram-v2)

**Comment by erenpakelgil** [comment]
@oguzhekim While reviewing the class diagram with @MertCengiz, we noticed that Comment class doesn't have user attribute that represents the registered user created that comment. Is there a specific reason for it or should we add a user attribute?

**Comment by oguzhekim** [comment]
You are right about Comment class. I fixed it. About the numOfLikes, I don't think we need it as an attribute because Like is a seperate class in the new diagram. It has methods called getNumberOfLikesForPost and getNumberOfLikesForComment which can return it whenever wanted. We can discuss this in the next meeting if you want. Also, we can move getNumberOfLikesForPost and getNumberOfLikesForComment methods to Post and Comment classes.

**Comment by erenpakelgil** [comment]
Retrieving the number of likes on a specific post from Like objects with corresponding post_id makes sense. If our class diagram is designed that way, it would be better imo not to move getNumberOfLikesForPost and getNumberOfLikesForComment from Like class since Post and Comment classes do not hold list of likes information. We can discuss this in the following meeting anyways.
